import { NextRequest } from 'next/server'
import { json, errorJson } from '@/lib/election'
import { requireOrganization } from '@/lib/org-context'
import { generateReport } from '@/lib/raei'

export const dynamic = 'force-dynamic'

// POST /api/raei/reports — Generate a report
// Body: { type, format, electionId?, organizationId?, dateRange? }
// format: JSON | CSV | PRINT (PRINT returns printable HTML)
export async function POST(req: NextRequest) {
  const orgResult = await requireOrganization(req)
  if ('error' in orgResult) return orgResult.error

  const body = await req.json().catch(() => ({}))
  if (!body.type) return errorJson('Report type is required', 400)

  try {
    const report = await generateReport({
      type: body.type,
      format: body.format || 'JSON',
      electionId: body.electionId,
      organizationId: orgResult.id,
      dateRange: body.dateRange,
    })

    // If PRINT format, return printable HTML
    if ((body.format || 'JSON').toUpperCase() === 'PRINT') {
      const html = renderPrintableReport(report)
      return new Response(html, {
        status: 200,
        headers: {
          'content-type': 'text/html; charset=utf-8',
          'content-disposition': `inline; filename="votewise-report-${report.type}.html"`,
        },
      })
    }

    // If CSV format, convert to CSV
    if ((body.format || 'JSON').toUpperCase() === 'CSV') {
      const csv = convertToCSV(report.data)
      return new Response(csv, {
        status: 200,
        headers: {
          'content-type': 'text/csv; charset=utf-8',
          'content-disposition': `attachment; filename="votewise-report-${report.type}.csv"`,
        },
      })
    }

    // Default: JSON
    return json(report)
  } catch (e: any) {
    return errorJson(e.message || 'Failed to generate report', 500)
  }
}

function renderPrintableReport(report: any): string {
  const title = report.data?.title || report.type
  const generated = new Date(report.generatedAt).toLocaleString()

  let body = ''
  if (report.data) {
    body = `<pre style="font-size:12px;line-height:1.6;white-space:pre-wrap;">${JSON.stringify(report.data, null, 2)}</pre>`
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>${title} — VoteWise Report</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1a1a1a; background: #fff; padding: 40px; }
  .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 3px solid #15803d; padding-bottom: 20px; margin-bottom: 30px; }
  .header h1 { font-size: 24px; color: #15803d; }
  .header .meta { text-align: right; font-size: 12px; color: #666; }
  .header .logo { font-weight: bold; font-size: 18px; color: #15803d; }
  .section { margin-bottom: 24px; }
  .section h2 { font-size: 16px; color: #15803d; margin-bottom: 8px; border-bottom: 1px solid #e5e5e5; padding-bottom: 4px; }
  .section table { width: 100%; border-collapse: collapse; font-size: 12px; }
  .section th { text-align: left; padding: 6px 8px; background: #f5f5f5; border: 1px solid #ddd; }
  .section td { padding: 6px 8px; border: 1px solid #ddd; }
  .footer { margin-top: 40px; border-top: 1px solid #ddd; padding-top: 12px; font-size: 10px; color: #999; text-align: center; }
  @media print { body { padding: 20px; } .no-print { display: none; } }
</style>
</head>
<body>
  <div class="header">
    <div>
      <div class="logo">VoteWise</div>
      <h1>${title}</h1>
    </div>
    <div class="meta">
      <div>Generated: ${generated}</div>
      <div>Type: ${report.type}</div>
      <div>Format: ${report.format}</div>
    </div>
  </div>
  <div class="section">
    ${body}
  </div>
  <div class="footer">
    This report was generated by VoteWise — Africa's Most Trusted Election Management Platform.<br/>
    Generated on ${generated} · Report ID: ${report.id}
  </div>
  <div class="no-print" style="margin-top:20px;text-align:center;">
    <button onclick="window.print()" style="padding:8px 24px;background:#15803d;color:white;border:none;border-radius:6px;cursor:pointer;font-size:14px;">Print Report</button>
  </div>
</body>
</html>`
}

function convertToCSV(data: any): string {
  if (!data || typeof data !== 'object') return ''

  // Flatten the data into CSV rows
  const rows: string[] = []
  const flatten = (obj: any, prefix = '') => {
    for (const [key, val] of Object.entries(obj)) {
      const fullKey = prefix ? `${prefix}.${key}` : key
      if (val && typeof val === 'object' && !Array.isArray(val)) {
        flatten(val, fullKey)
      } else if (Array.isArray(val)) {
        rows.push(`${fullKey},${val.length} items`)
      } else {
        rows.push(`${fullKey},${String(val || '').replace(/,/g, ';')}`)
      }
    }
  }
  flatten(data)
  return 'Field,Value\n' + rows.join('\n')
}
